### PR TITLE
Fix retrieving wireless interfaces

### PR DESCRIPTION
**Pull request by Trekky12**
This fixes issue #8

### CODE REVIEW

**Comment by newkit** [comment]
Thank you  @Trekky12 for your PR! Did you check with an older (<23.05) version that the iwinfo command works there, too?

**Comment by Trekky12** [comment]
I have checked 22.03 and since this method is in the official documentation (https://openwrt.org/faq/how_to_get_a_list_of_connected_clients) which was

> written for openwrt 12.09 Attitude Adjustment

I think it should work in several older versions too.

**Comment by newkit** [comment]
Thanks for checking @Trekky12 .

**Comment by Trekky12** [comment]
Thank you very much for accepting the PR @newkit.
Do you know how it could be added to the official packages?

**Comment by newkit** [comment]
Well, someone (you|me ;-) has to update the packages via a PR here https://github.com/openwrt/packages :-D

**Comment by Trekky12** [comment]
Could you do that? 😊

**Comment by newkit** [comment]
> Could you do that? 😊

https://github.com/openwrt/packages/pull/22648

**Comment by sNiXx** [comment]
I saw on GitHub that the package was updated recently to 1.1.0. However, I can still only see version 1-3 when I check with opkg. Updates for other packages are visible, so do you have any ideas why this could be the case? I am currently on 23.05.5

**Pull request merged**
